### ISSUE TITLE
Profiling django manage.py runserver

### ISSUE THREAD

**Issue by somghosh** [asottile/importtime-waterfall#101]
I came here from this post https://forum.djangoproject.com/t/slow-runserver-start-up-how-to-debug/15078  from @adamchainz 

I am trying to do

```
$ importtime-waterfall --include-interpreter-startup manage.py runserver
usage: importtime-waterfall [-h] [--include-interpreter-startup]
                            [--graph | --har]
                            module
importtime-waterfall: error: unrecognized arguments: runserver
```

However this does not work, seems I can only add a single word/command as "module"argument

however `python3 -Ximporttime  manage.py runserver` works. Any idea how I can use your package so I can get a better visual of manage.py runserver (final aim is to understand why it is slow)

![image](https://user-images.githubusercontent.com/5731118/219944359-4f4e3247-c32e-47ee-a14c-b1cc82a5d3bb.png)

**Comment by asottile** [comment]
importtime-waterfall is only for measuring the import time at startup via importing a module you want to profile.  you probably want to use a more generalized profiling tool https://youtu.be/ey_P64E34g0

**Comment by adamchainz** [comment]
It's true that to profile the actual `runserver`, you'll need a full profiler, as running the server actually runs a whole command, not just imports.

But you can measure much of your Django startup slowness with a short module that initializes Django with your settings.

For example, put in `example.py` next to `manage.py`:

```python
import os
import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "example.settings")
django.setup()
```

Then you can run:

```
importtime-waterfall example
```

or with `--har`, which is very useful.

**Comment by somghosh** [comment]
hi @adamchainz  Thanks. Yes with this script `importtime-waterfall` works :)

However, I dont think the time taken for loading this script is similar to the time taken for `runserver`

```

## django_load_time_test_script.py
## this is the test script as in your comment

import os
import django

os.environ.setdefault("DJANGO_SETTINGS_MODULE", "xenia.settings")
django.setup()

```


```

$ command time -p python django_load_time_test_script.py  

real 2.47
user 2.72
sys 0.65

```


However  runserver start time is much larger


```
command time -p python manage.py runserver 0.0.0.0:8080

Starting development server at http://0.0.0.0:8080/
Quit the server with CONTROL-C.
Error: That port is already in use. # to ensure that there is no extra time recorded I already run another runserver on same port so that this one exits straight away to record accurate time

real 8.89
user 8.94
sys 2.29


```

**Comment by adamchainz** [comment]
This conversation inspired me to write a blog post about profiling django projects with importtime-waterfall and cprofile, and techniques to reduce/defer import time: https://adamj.eu/tech/2023/03/02/django-profile-and-improve-import-time/
