### ISSUE TITLE
No executable command provided and no output

### ISSUE THREAD

**Issue by lnevay** [asottile/importtime-waterfall#54]
Hello,

I can't get this package to work at all.  I installed via pip (21.3.1) and python3.9 and I can successfully import it in python.

The entry point doesn't appear for me in bash (Mac OS 11.6.1, python3.9 from macports).  Can't see how to execute or use this manually through python - no instructions for this.  I tried:

```python -X importtime_waterfall --har ~/importmypackage.py```

where `importmypackage.py` just does  ```import mypackage```.  This works fine with the regular importtime.

The above command runs but produces no output whatsover.  No print out, no files.

**Comment by asottile** [comment]
I don't know where you found the command you're trying but the readme has several examples of how to use this and none of them look like what you've tried: https://github.com/asottile/importtime-waterfall#usage

**Comment by lnevay** [comment]
Hello - thanks for getting back so quickly!

The readme says use the entry point like this

```
importtime-waterfall importtime_waterfall --har | xclip -selection c
-bash: importtime-waterfall: command not found
```
The entry point doesn't work for me despite it being installed ok with pip.  This is likely a macports / mac / permissions thing.

How can I use it without that entry point?  The command I used it based on how you would use the conventional importtime.

**Comment by asottile** [comment]
can you show the pip install output? it should have printed a warning that you perhaps ignored?
