### ISSUE TITLE
Sort --graph output by cumulative time 

### ISSUE THREAD

**Issue by lemon24** [asottile/importtime-waterfall#94]
(follow-up to https://github.com/asottile/importtime-waterfall/pull/93)

It would be useful to sort the modules in the --graph output that have the same "parent" by cumulative time, descending (and also show it for each module). Example output [here](https://github.com/asottile/importtime-waterfall/blob/0a11e9cdf9ea33f5008bbfd294f47e543c93794d/README.md#--graph).

The reasoning is when using this to optimize imports, one is mostly interested in modules that take the most time.

In the simplest implementation, this would be the only order (like in #93); sorting by name or self time doesn't seem very useful (idem for the "default" order?). Barring this, a `-s cumulative|none` option would also work (a la cProfile).

**Comment by asottile** [comment]
I don't think showing in any order other than execution order makes sense.  cumulative for imports doesn't really make sense because imports are only executed once (earlier imports will tend to have more bias in cumulative time because their sub-imports won't be counted against future imports)

it's also the reason cumulative time is intentionally omitted in the output (despite being present in `-Ximporttime`)

**Comment by lemon24** [comment]
For me (deciding what/if to lazy-import), it was useful despite the bias, because not all modules in a package import all the dependencies. Specifically, there are some (big-ish) dependencies that are only imported by one module each.

I was able to halve the import time for the most common use case of my package by adding just 2 lazy imports (requests and bs4 below). Sorting by cumulative time makes it easy to see what those modules are by following from the top, along the larger cumulative times (also made easier by --max-depth proposed in #95):

```
importreader (319624, 2175)
  reader (288755, 388)
    reader.core (288367, 1112)
      reader._parser (148664, 2367)
        reader._requests_utils (92812, 1687)
            requests (91106, 458)
              urllib3 (53114, 493)
        reader._types (33868, 4897)
          reader.types (28783, 11226)
            reader._utils (16901, 1244)
              multiprocessing.dummy (15657, 1391)
      reader._search (119990, 698)
        reader._html_utils (111905, 351)
          bs4 (111554, 591)
  reader._feedparser (24056, 352)
    reader._vendor.feedparser (23704, 200)
      reader._vendor.feedparser.api (23504, 597)
```

Also, I found this kind of output useful to show (in issue comments) how adding various lazy imports changed the total time, or didn't.

**Comment by asottile** [comment]
yeah I'm not going to change my tool to something I would recommend against -- going to stick to "do one thing well" and not bloat with a bunch of options that obscure the truth

**Comment by asottile** [comment]
I think perhaps a more reasonable request would be a `--json` output which gives you the raw data to transform into whatever format you might want

**Comment by lemon24** [comment]
No worries, thanks for providing a bit of code that was easy to modify to do what I needed it to do! :)

---

>  a --json output 

Either this, or just expose the [main logic](https://github.com/asottile/importtime-waterfall/blob/a74d8f4557178577fcd5cd9b0bcad1b821f49512/importtime_waterfall.py#L139-L165) in a separate `def (module: str, include_interpreter_startup: bool) -> Import` function. (Looking back at how I used this, it doesn't even have to be stable, I'm fine with changing my quick-and-dirty output script in a month if it breaks.)
