### ISSUE TITLE
(optionally) limit the depth of the --graph output

### ISSUE THREAD

**Issue by lemon24** [asottile/importtime-waterfall#95]
(follow-up to https://github.com/asottile/importtime-waterfall/pull/93)

Sometimes, it's useful to limit the depth of the --graph output; e.g. to get a summary to paste in an issue, or because the output is too large to follow easily (and one doesn't need it to descend into external dependencies).

Proposed implementation: a `--max-depth X` option (like in #93). Example output [here](https://github.com/asottile/importtime-waterfall/blob/0a11e9cdf9ea33f5008bbfd294f47e543c93794d/README.md#--max-depth-and---hide-under).

**Comment by asottile** [comment]
I'm not sure the use case warrants the complexity -- if you're pasting into an issue you can just remove the lines that aren't relevant

**Comment by asottile** [comment]
this doesn't make sense without aggregating which I'm against so I'm going to close this

**Comment by lemon24** [comment]
It's useful if you paste it repeatedly, while doing more and more changes.

This would entail a parser.add_argument() for the option, passing it along to graph(), and an if to return early from pp() (+3 lines). The --har logic is unaffected. (Of course, your call on what's too much.)

---

> this doesn't make sense without aggregating which I'm against so I'm going to close this

Agree. (My bad, I forgot to mention I was using this with the cumulative time output proposed in #94.)
